2020-06-27 11:18:33,559 - INFO - my_logging logger is started. Console : DEBUG. File (index.log) : INFO at /usr/local/lib/python2.7/dist-packages/FUTIL/my_logging.py ,line nÂ°:104
2020-06-27 11:19:17,714 - INFO - my_logging logger is started. Console : DEBUG. File (index.log) : INFO at /usr/local/lib/python2.7/dist-packages/FUTIL/my_logging.py ,line nÂ°:104
2020-06-27 11:19:18,403 - INFO -  * Running on http://0.0.0.0:50889/ (Press CTRL+C to quit) at /usr/local/lib/python2.7/dist-packages/werkzeug/_internal.py ,line nÂ°:122
2020-06-27 11:19:18,440 - INFO -  * Restarting with stat at /usr/local/lib/python2.7/dist-packages/werkzeug/_internal.py ,line nÂ°:122
2020-06-27 11:19:18,497 - ERROR -   File "index.py", line 36, in <module>
    app.run(host='0.0.0.0', port=50889, debug=True)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 944, in run
    run_simple(host, port, self, **options)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 1007, in run_simple
    run_with_reloader(inner, extra_files, reloader_interval, reloader_type)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/_reloader.py", line 332, in run_with_reloader
    sys.exit(reloader.restart_with_reloader())
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/_reloader.py", line 176, in restart_with_reloader
    exit_code = subprocess.call(args, env=new_environ, close_fds=False)
  File "/usr/lib/python2.7/subprocess.py", line 523, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
 at /usr/local/lib/python2.7/dist-packages/FUTIL/my_logging.py ,line nÂ°:183
2020-06-27 11:19:18,500 - ERROR - <type 'exceptions.OSError'> - [Errno 8] Exec format error at /usr/local/lib/python2.7/dist-packages/FUTIL/my_logging.py ,line nÂ°:184
2020-06-27 11:21:18,141 - INFO - my_logging logger is started. Console : DEBUG. File (index.log) : INFO at /usr/local/lib/python2.7/dist-packages/FUTIL/my_logging.py ,line nÂ°:104
2020-06-27 11:21:18,258 - INFO -  * Running on http://0.0.0.0:50889/ (Press CTRL+C to quit) at /usr/local/lib/python2.7/dist-packages/werkzeug/_internal.py ,line nÂ°:122
2020-06-27 11:21:18,261 - INFO -  * Restarting with stat at /usr/local/lib/python2.7/dist-packages/werkzeug/_internal.py ,line nÂ°:122
2020-06-27 11:21:18,277 - ERROR -   File "index.py", line 37, in <module>
    app.run(host='0.0.0.0', port=50889, debug=True)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 944, in run
    run_simple(host, port, self, **options)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 1007, in run_simple
    run_with_reloader(inner, extra_files, reloader_interval, reloader_type)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/_reloader.py", line 332, in run_with_reloader
    sys.exit(reloader.restart_with_reloader())
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/_reloader.py", line 176, in restart_with_reloader
    exit_code = subprocess.call(args, env=new_environ, close_fds=False)
  File "/usr/lib/python2.7/subprocess.py", line 523, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
 at /usr/local/lib/python2.7/dist-packages/FUTIL/my_logging.py ,line nÂ°:183
2020-06-27 11:21:18,279 - ERROR - <type 'exceptions.OSError'> - [Errno 8] Exec format error at /usr/local/lib/python2.7/dist-packages/FUTIL/my_logging.py ,line nÂ°:184
2020-06-27 11:24:34,991 - INFO - my_logging logger is started. Console : DEBUG. File (index.log) : INFO at /home/fred/.local/lib/python3.5/site-packages/FUTIL/my_logging.py ,line nÂ°:104
2020-06-27 11:24:35,199 - INFO -  * Running on http://0.0.0.0:50889/ (Press CTRL+C to quit) at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 11:24:35,205 - INFO -  * Restarting with stat at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 11:24:35,470 - INFO - my_logging logger is started. Console : DEBUG. File (/mnt/c/Users/FrÃ©dÃ©ric/Devlopp/t-home/src/pyserve/index.log) : INFO at /home/fred/.local/lib/python3.5/site-packages/FUTIL/my_logging.py ,line nÂ°:104
2020-06-27 11:24:35,573 - WARNING -  * Debugger is active! at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 11:24:35,581 - INFO -  * Debugger PIN: 267-078-036 at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 11:25:01,523 - INFO - 127.0.0.1 - - [27/Jun/2020 11:25:01] "[31m[1mGET / HTTP/1.1[0m" 401 - at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 11:25:13,978 - INFO - 127.0.0.1 - - [27/Jun/2020 11:25:13] "[37mGET / HTTP/1.1[0m" 200 - at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 11:25:14,345 - INFO - 127.0.0.1 - - [27/Jun/2020 11:25:14] "[33mGET /favicon.ico HTTP/1.1[0m" 404 - at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 11:26:57,675 - INFO -  * Detected change in '/mnt/c/Users/FrÃ©dÃ©ric/Devlopp/t-home/src/pyserve/index.py', reloading at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 11:26:57,717 - INFO -  * Restarting with stat at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 11:26:57,963 - INFO - my_logging logger is started. Console : DEBUG. File (/mnt/c/Users/FrÃ©dÃ©ric/Devlopp/t-home/src/pyserve/index.log) : INFO at /home/fred/.local/lib/python3.5/site-packages/FUTIL/my_logging.py ,line nÂ°:104
2020-06-27 11:26:58,073 - WARNING -  * Debugger is active! at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 11:26:58,074 - INFO -  * Debugger PIN: 267-078-036 at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 11:27:04,255 - INFO - 127.0.0.1 - - [27/Jun/2020 11:27:04] "[37mGET /t-home HTTP/1.1[0m" 200 - at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:09:53,533 - INFO - my_logging logger is started. Console : DEBUG. File (index.log) : INFO at /home/fred/.local/lib/python3.5/site-packages/FUTIL/my_logging.py ,line nÂ°:104
2020-06-27 12:09:54,630 - INFO -  * Running on http://0.0.0.0:50889/ (Press CTRL+C to quit) at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:09:54,631 - INFO -  * Restarting with stat at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:09:54,866 - INFO - my_logging logger is started. Console : DEBUG. File (/mnt/c/Users/FrÃ©dÃ©ric/Devlopp/t-home/src/pyserve/index.log) : INFO at /home/fred/.local/lib/python3.5/site-packages/FUTIL/my_logging.py ,line nÂ°:104
2020-06-27 12:09:55,076 - WARNING -  * Debugger is active! at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:09:55,078 - INFO -  * Debugger PIN: 267-078-036 at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:10:00,743 - INFO - 127.0.0.1 - - [27/Jun/2020 12:10:00] "[37mGET /t-home HTTP/1.1[0m" 200 - at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:10:13,415 - INFO - 127.0.0.1 - - [27/Jun/2020 12:10:13] "[35m[1mGET /t-home?id=test HTTP/1.1[0m" 500 - at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:10:13,440 - INFO - 127.0.0.1 - - [27/Jun/2020 12:10:13] "[37mGET /t-home?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 200 - at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:10:13,441 - INFO - 127.0.0.1 - - [27/Jun/2020 12:10:13] "[37mGET /t-home?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1[0m" 200 - at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:10:13,441 - INFO - 127.0.0.1 - - [27/Jun/2020 12:10:13] "[37mGET /t-home?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 200 - at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:10:13,569 - INFO - 127.0.0.1 - - [27/Jun/2020 12:10:13] "[37mGET /t-home?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1[0m" 200 - at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:10:13,597 - INFO - 127.0.0.1 - - [27/Jun/2020 12:10:13] "[37mGET /t-home?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 - at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:10:13,635 - INFO - 127.0.0.1 - - [27/Jun/2020 12:10:13] "[37mGET /t-home?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 - at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:12:48,040 - INFO -  * Detected change in '/mnt/c/Users/FrÃ©dÃ©ric/Devlopp/t-home/src/pyserve/tempeDB.py', reloading at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:12:48,092 - INFO -  * Restarting with stat at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:12:48,369 - INFO - my_logging logger is started. Console : DEBUG. File (/mnt/c/Users/FrÃ©dÃ©ric/Devlopp/t-home/src/pyserve/index.log) : INFO at /home/fred/.local/lib/python3.5/site-packages/FUTIL/my_logging.py ,line nÂ°:104
2020-06-27 12:12:49,003 - WARNING -  * Debugger is active! at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:12:49,004 - INFO -  * Debugger PIN: 267-078-036 at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:12:54,153 - INFO - 127.0.0.1 - - [27/Jun/2020 12:12:54] "[35m[1mGET /t-home?id=test HTTP/1.1[0m" 500 - at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:12:54,184 - INFO - 127.0.0.1 - - [27/Jun/2020 12:12:54] "[37mGET /t-home?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 200 - at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:12:54,185 - INFO - 127.0.0.1 - - [27/Jun/2020 12:12:54] "[37mGET /t-home?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1[0m" 200 - at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:12:54,185 - INFO - 127.0.0.1 - - [27/Jun/2020 12:12:54] "[37mGET /t-home?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 200 - at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:12:54,268 - INFO - 127.0.0.1 - - [27/Jun/2020 12:12:54] "[37mGET /t-home?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1[0m" 200 - at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:12:54,299 - INFO - 127.0.0.1 - - [27/Jun/2020 12:12:54] "[37mGET /t-home?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 - at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:12:54,352 - INFO - 127.0.0.1 - - [27/Jun/2020 12:12:54] "[37mGET /t-home?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 - at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:13:19,643 - INFO -  * Detected change in '/mnt/c/Users/FrÃ©dÃ©ric/Devlopp/t-home/src/pyserve/tempeDB.py', reloading at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:13:19,700 - INFO -  * Restarting with stat at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:13:19,944 - INFO - my_logging logger is started. Console : DEBUG. File (/mnt/c/Users/FrÃ©dÃ©ric/Devlopp/t-home/src/pyserve/index.log) : INFO at /home/fred/.local/lib/python3.5/site-packages/FUTIL/my_logging.py ,line nÂ°:104
2020-06-27 12:13:20,140 - WARNING -  * Debugger is active! at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:13:20,141 - INFO -  * Debugger PIN: 267-078-036 at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:13:21,632 - INFO - 127.0.0.1 - - [27/Jun/2020 12:13:21] "[35m[1mGET /t-home?id=test HTTP/1.1[0m" 500 - at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:13:21,659 - INFO - 127.0.0.1 - - [27/Jun/2020 12:13:21] "[37mGET /t-home?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 200 - at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:13:21,660 - INFO - 127.0.0.1 - - [27/Jun/2020 12:13:21] "[37mGET /t-home?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1[0m" 200 - at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:13:21,661 - INFO - 127.0.0.1 - - [27/Jun/2020 12:13:21] "[37mGET /t-home?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 200 - at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:13:21,752 - INFO - 127.0.0.1 - - [27/Jun/2020 12:13:21] "[37mGET /t-home?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1[0m" 200 - at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:13:21,791 - INFO - 127.0.0.1 - - [27/Jun/2020 12:13:21] "[37mGET /t-home?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 - at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:13:21,850 - INFO - 127.0.0.1 - - [27/Jun/2020 12:13:21] "[37mGET /t-home?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 - at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:14:09,254 - INFO -  * Detected change in '/mnt/c/Users/FrÃ©dÃ©ric/Devlopp/t-home/src/pyserve/tempeDB.py', reloading at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:14:09,321 - INFO -  * Restarting with stat at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:14:09,579 - INFO - my_logging logger is started. Console : DEBUG. File (/mnt/c/Users/FrÃ©dÃ©ric/Devlopp/t-home/src/pyserve/index.log) : INFO at /home/fred/.local/lib/python3.5/site-packages/FUTIL/my_logging.py ,line nÂ°:104
2020-06-27 12:14:09,827 - WARNING -  * Debugger is active! at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:14:09,828 - INFO -  * Debugger PIN: 267-078-036 at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:14:11,593 - INFO - 127.0.0.1 - - [27/Jun/2020 12:14:11] "[35m[1mGET /t-home?id=test HTTP/1.1[0m" 500 - at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:14:11,621 - INFO - 127.0.0.1 - - [27/Jun/2020 12:14:11] "[37mGET /t-home?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 200 - at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:14:11,621 - INFO - 127.0.0.1 - - [27/Jun/2020 12:14:11] "[37mGET /t-home?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1[0m" 200 - at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:14:11,622 - INFO - 127.0.0.1 - - [27/Jun/2020 12:14:11] "[37mGET /t-home?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 200 - at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:14:11,694 - INFO - 127.0.0.1 - - [27/Jun/2020 12:14:11] "[37mGET /t-home?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1[0m" 200 - at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:14:11,724 - INFO - 127.0.0.1 - - [27/Jun/2020 12:14:11] "[37mGET /t-home?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 - at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:14:11,775 - INFO - 127.0.0.1 - - [27/Jun/2020 12:14:11] "[37mGET /t-home?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 - at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:16:11,488 - INFO -  * Detected change in '/mnt/c/Users/FrÃ©dÃ©ric/Devlopp/t-home/src/pyserve/tempeDB.py', reloading at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:16:11,547 - INFO -  * Restarting with stat at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:16:11,809 - INFO - my_logging logger is started. Console : DEBUG. File (/mnt/c/Users/FrÃ©dÃ©ric/Devlopp/t-home/src/pyserve/index.log) : INFO at /home/fred/.local/lib/python3.5/site-packages/FUTIL/my_logging.py ,line nÂ°:104
2020-06-27 12:16:12,337 - WARNING -  * Debugger is active! at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:16:12,339 - INFO -  * Debugger PIN: 267-078-036 at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:16:25,778 - INFO - 127.0.0.1 - - [27/Jun/2020 12:16:25] "[35m[1mGET /t-home?id=test HTTP/1.1[0m" 500 - at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:16:25,804 - INFO - 127.0.0.1 - - [27/Jun/2020 12:16:25] "[37mGET /t-home?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 200 - at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:16:25,805 - INFO - 127.0.0.1 - - [27/Jun/2020 12:16:25] "[37mGET /t-home?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1[0m" 200 - at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:16:25,806 - INFO - 127.0.0.1 - - [27/Jun/2020 12:16:25] "[37mGET /t-home?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 200 - at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:16:25,884 - INFO - 127.0.0.1 - - [27/Jun/2020 12:16:25] "[37mGET /t-home?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1[0m" 200 - at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:16:25,914 - INFO - 127.0.0.1 - - [27/Jun/2020 12:16:25] "[37mGET /t-home?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 - at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:16:25,966 - INFO - 127.0.0.1 - - [27/Jun/2020 12:16:25] "[37mGET /t-home?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 - at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:16:57,298 - INFO -  * Detected change in '/mnt/c/Users/FrÃ©dÃ©ric/Devlopp/t-home/src/pyserve/tempeDB.py', reloading at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:16:57,352 - INFO -  * Restarting with stat at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:16:57,601 - INFO - my_logging logger is started. Console : DEBUG. File (/mnt/c/Users/FrÃ©dÃ©ric/Devlopp/t-home/src/pyserve/index.log) : INFO at /home/fred/.local/lib/python3.5/site-packages/FUTIL/my_logging.py ,line nÂ°:104
2020-06-27 12:16:57,891 - WARNING -  * Debugger is active! at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:16:57,892 - INFO -  * Debugger PIN: 267-078-036 at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:17:42,519 - INFO - 127.0.0.1 - - [27/Jun/2020 12:17:42] "[35m[1mGET /t-home?id=test HTTP/1.1[0m" 500 - at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:17:42,553 - INFO - 127.0.0.1 - - [27/Jun/2020 12:17:42] "[37mGET /t-home?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 200 - at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:17:42,555 - INFO - 127.0.0.1 - - [27/Jun/2020 12:17:42] "[37mGET /t-home?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1[0m" 200 - at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:17:42,558 - INFO - 127.0.0.1 - - [27/Jun/2020 12:17:42] "[37mGET /t-home?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 200 - at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:17:42,618 - INFO - 127.0.0.1 - - [27/Jun/2020 12:17:42] "[37mGET /t-home?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1[0m" 200 - at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:17:42,646 - INFO - 127.0.0.1 - - [27/Jun/2020 12:17:42] "[37mGET /t-home?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 - at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:17:42,714 - INFO - 127.0.0.1 - - [27/Jun/2020 12:17:42] "[37mGET /t-home?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 - at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:18:34,155 - INFO -  * Detected change in '/mnt/c/Users/FrÃ©dÃ©ric/Devlopp/t-home/src/pyserve/tempeDB.py', reloading at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:18:34,198 - INFO -  * Restarting with stat at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:18:34,451 - INFO - my_logging logger is started. Console : DEBUG. File (/mnt/c/Users/FrÃ©dÃ©ric/Devlopp/t-home/src/pyserve/index.log) : INFO at /home/fred/.local/lib/python3.5/site-packages/FUTIL/my_logging.py ,line nÂ°:104
2020-06-27 12:18:34,914 - WARNING -  * Debugger is active! at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:18:34,915 - INFO -  * Debugger PIN: 267-078-036 at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:18:36,107 - INFO - 127.0.0.1 - - [27/Jun/2020 12:18:36] "[35m[1mGET /t-home?id=test HTTP/1.1[0m" 500 - at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:18:36,136 - INFO - 127.0.0.1 - - [27/Jun/2020 12:18:36] "[37mGET /t-home?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 200 - at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:18:36,137 - INFO - 127.0.0.1 - - [27/Jun/2020 12:18:36] "[37mGET /t-home?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1[0m" 200 - at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:18:36,138 - INFO - 127.0.0.1 - - [27/Jun/2020 12:18:36] "[37mGET /t-home?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 200 - at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:18:36,199 - INFO - 127.0.0.1 - - [27/Jun/2020 12:18:36] "[37mGET /t-home?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1[0m" 200 - at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:18:36,231 - INFO - 127.0.0.1 - - [27/Jun/2020 12:18:36] "[37mGET /t-home?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 - at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:18:36,303 - INFO - 127.0.0.1 - - [27/Jun/2020 12:18:36] "[37mGET /t-home?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 - at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:19:00,493 - INFO -  * Detected change in '/mnt/c/Users/FrÃ©dÃ©ric/Devlopp/t-home/src/pyserve/tempeDB.py', reloading at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:19:00,550 - INFO -  * Restarting with stat at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:19:00,808 - INFO - my_logging logger is started. Console : DEBUG. File (/mnt/c/Users/FrÃ©dÃ©ric/Devlopp/t-home/src/pyserve/index.log) : INFO at /home/fred/.local/lib/python3.5/site-packages/FUTIL/my_logging.py ,line nÂ°:104
2020-06-27 12:19:01,009 - WARNING -  * Debugger is active! at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:19:01,010 - INFO -  * Debugger PIN: 267-078-036 at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:19:02,939 - INFO - 127.0.0.1 - - [27/Jun/2020 12:19:02] "[35m[1mGET /t-home?id=test HTTP/1.1[0m" 500 - at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:19:02,964 - INFO - 127.0.0.1 - - [27/Jun/2020 12:19:02] "[37mGET /t-home?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 200 - at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:19:02,969 - INFO - 127.0.0.1 - - [27/Jun/2020 12:19:02] "[37mGET /t-home?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 200 - at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:19:02,970 - INFO - 127.0.0.1 - - [27/Jun/2020 12:19:02] "[37mGET /t-home?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1[0m" 200 - at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:19:03,045 - INFO - 127.0.0.1 - - [27/Jun/2020 12:19:03] "[37mGET /t-home?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1[0m" 200 - at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:19:03,077 - INFO - 127.0.0.1 - - [27/Jun/2020 12:19:03] "[37mGET /t-home?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 - at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:19:03,134 - INFO - 127.0.0.1 - - [27/Jun/2020 12:19:03] "[37mGET /t-home?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 - at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:19:27,653 - INFO -  * Detected change in '/mnt/c/Users/FrÃ©dÃ©ric/Devlopp/t-home/src/pyserve/tempeDB.py', reloading at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:19:27,734 - INFO -  * Restarting with stat at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:19:27,985 - INFO - my_logging logger is started. Console : DEBUG. File (/mnt/c/Users/FrÃ©dÃ©ric/Devlopp/t-home/src/pyserve/index.log) : INFO at /home/fred/.local/lib/python3.5/site-packages/FUTIL/my_logging.py ,line nÂ°:104
2020-06-27 12:19:28,161 - WARNING -  * Debugger is active! at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:19:28,163 - INFO -  * Debugger PIN: 267-078-036 at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:19:29,919 - INFO - 127.0.0.1 - - [27/Jun/2020 12:19:29] "[35m[1mGET /t-home?id=test HTTP/1.1[0m" 500 - at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:19:29,949 - INFO - 127.0.0.1 - - [27/Jun/2020 12:19:29] "[37mGET /t-home?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 200 - at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:19:29,949 - INFO - 127.0.0.1 - - [27/Jun/2020 12:19:29] "[37mGET /t-home?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1[0m" 200 - at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:19:29,950 - INFO - 127.0.0.1 - - [27/Jun/2020 12:19:29] "[37mGET /t-home?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 200 - at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:19:30,035 - INFO - 127.0.0.1 - - [27/Jun/2020 12:19:30] "[37mGET /t-home?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1[0m" 200 - at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:19:30,066 - INFO - 127.0.0.1 - - [27/Jun/2020 12:19:30] "[37mGET /t-home?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 - at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:19:30,120 - INFO - 127.0.0.1 - - [27/Jun/2020 12:19:30] "[37mGET /t-home?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 - at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:24:23,101 - INFO -  * Detected change in '/mnt/c/Users/FrÃ©dÃ©ric/Devlopp/t-home/src/pyserve/tempeDB.py', reloading at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:24:23,145 - INFO -  * Restarting with stat at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:24:23,398 - INFO - my_logging logger is started. Console : DEBUG. File (/mnt/c/Users/FrÃ©dÃ©ric/Devlopp/t-home/src/pyserve/index.log) : INFO at /home/fred/.local/lib/python3.5/site-packages/FUTIL/my_logging.py ,line nÂ°:104
2020-06-27 12:24:24,069 - WARNING -  * Debugger is active! at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:24:24,070 - INFO -  * Debugger PIN: 267-078-036 at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:24:27,353 - INFO - 127.0.0.1 - - [27/Jun/2020 12:24:27] "[35m[1mGET /t-home?id=test HTTP/1.1[0m" 500 - at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:24:27,380 - INFO - 127.0.0.1 - - [27/Jun/2020 12:24:27] "[37mGET /t-home?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 200 - at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:24:27,381 - INFO - 127.0.0.1 - - [27/Jun/2020 12:24:27] "[37mGET /t-home?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 200 - at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:24:27,381 - INFO - 127.0.0.1 - - [27/Jun/2020 12:24:27] "[37mGET /t-home?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1[0m" 200 - at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:24:27,462 - INFO - 127.0.0.1 - - [27/Jun/2020 12:24:27] "[37mGET /t-home?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1[0m" 200 - at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:24:27,492 - INFO - 127.0.0.1 - - [27/Jun/2020 12:24:27] "[37mGET /t-home?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 - at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:24:27,548 - INFO - 127.0.0.1 - - [27/Jun/2020 12:24:27] "[37mGET /t-home?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 - at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:24:42,460 - INFO -  * Detected change in '/mnt/c/Users/FrÃ©dÃ©ric/Devlopp/t-home/src/pyserve/tempeDB.py', reloading at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:24:42,510 - INFO -  * Restarting with stat at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:24:42,768 - INFO - my_logging logger is started. Console : DEBUG. File (/mnt/c/Users/FrÃ©dÃ©ric/Devlopp/t-home/src/pyserve/index.log) : INFO at /home/fred/.local/lib/python3.5/site-packages/FUTIL/my_logging.py ,line nÂ°:104
2020-06-27 12:24:43,034 - WARNING -  * Debugger is active! at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:24:43,035 - INFO -  * Debugger PIN: 267-078-036 at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:24:44,666 - INFO - 127.0.0.1 - - [27/Jun/2020 12:24:44] "[35m[1mGET /t-home?id=test HTTP/1.1[0m" 500 - at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:24:44,709 - INFO - 127.0.0.1 - - [27/Jun/2020 12:24:44] "[37mGET /t-home?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 200 - at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:24:44,711 - INFO - 127.0.0.1 - - [27/Jun/2020 12:24:44] "[37mGET /t-home?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1[0m" 200 - at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:24:44,712 - INFO - 127.0.0.1 - - [27/Jun/2020 12:24:44] "[37mGET /t-home?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 200 - at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:24:44,797 - INFO - 127.0.0.1 - - [27/Jun/2020 12:24:44] "[37mGET /t-home?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1[0m" 200 - at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:24:44,829 - INFO - 127.0.0.1 - - [27/Jun/2020 12:24:44] "[37mGET /t-home?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 - at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:24:44,882 - INFO - 127.0.0.1 - - [27/Jun/2020 12:24:44] "[37mGET /t-home?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 - at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:25:40,144 - INFO -  * Detected change in '/mnt/c/Users/FrÃ©dÃ©ric/Devlopp/t-home/src/pyserve/tempeDB.py', reloading at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:25:40,185 - INFO -  * Restarting with stat at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:25:40,437 - INFO - my_logging logger is started. Console : DEBUG. File (/mnt/c/Users/FrÃ©dÃ©ric/Devlopp/t-home/src/pyserve/index.log) : INFO at /home/fred/.local/lib/python3.5/site-packages/FUTIL/my_logging.py ,line nÂ°:104
2020-06-27 12:25:40,629 - WARNING -  * Debugger is active! at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:25:40,630 - INFO -  * Debugger PIN: 267-078-036 at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:25:42,914 - INFO - 127.0.0.1 - - [27/Jun/2020 12:25:42] "[35m[1mGET /t-home?id=test HTTP/1.1[0m" 500 - at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:25:42,955 - INFO - 127.0.0.1 - - [27/Jun/2020 12:25:42] "[37mGET /t-home?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 200 - at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:25:42,956 - INFO - 127.0.0.1 - - [27/Jun/2020 12:25:42] "[37mGET /t-home?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1[0m" 200 - at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:25:42,957 - INFO - 127.0.0.1 - - [27/Jun/2020 12:25:42] "[37mGET /t-home?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 200 - at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:25:43,030 - INFO - 127.0.0.1 - - [27/Jun/2020 12:25:43] "[37mGET /t-home?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1[0m" 200 - at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:25:43,064 - INFO - 127.0.0.1 - - [27/Jun/2020 12:25:43] "[37mGET /t-home?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 - at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:25:43,120 - INFO - 127.0.0.1 - - [27/Jun/2020 12:25:43] "[37mGET /t-home?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 - at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:42:20,365 - INFO -  * Detected change in '/mnt/c/Users/FrÃ©dÃ©ric/Devlopp/t-home/src/pyserve/tempeDB.py', reloading at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:42:20,450 - INFO -  * Restarting with stat at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:42:20,706 - INFO - my_logging logger is started. Console : DEBUG. File (/mnt/c/Users/FrÃ©dÃ©ric/Devlopp/t-home/src/pyserve/index.log) : INFO at /home/fred/.local/lib/python3.5/site-packages/FUTIL/my_logging.py ,line nÂ°:104
2020-06-27 12:42:21,725 - WARNING -  * Debugger is active! at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:42:21,726 - INFO -  * Debugger PIN: 267-078-036 at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:42:26,520 - INFO - 127.0.0.1 - - [27/Jun/2020 12:42:26] "[37mGET /t-home?id=test HTTP/1.1[0m" 200 - at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:54:00,646 - INFO -  * Detected change in '/mnt/c/Users/FrÃ©dÃ©ric/Devlopp/t-home/src/pyserve/index.py', reloading at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:54:00,693 - INFO -  * Restarting with stat at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:54:00,957 - INFO - my_logging logger is started. Console : DEBUG. File (/mnt/c/Users/FrÃ©dÃ©ric/Devlopp/t-home/src/pyserve/index.log) : INFO at /home/fred/.local/lib/python3.5/site-packages/FUTIL/my_logging.py ,line nÂ°:104
2020-06-27 12:54:01,665 - WARNING -  * Debugger is active! at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:54:01,666 - INFO -  * Debugger PIN: 267-078-036 at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 12:54:12,946 - INFO - 127.0.0.1 - - [27/Jun/2020 12:54:12] "[37mGET /tempeDB?id=test HTTP/1.1[0m" 200 - at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 16:58:28,640 - INFO - my_logging logger is started. Console : DEBUG. File (index.log) : INFO at /home/fred/.local/lib/python3.5/site-packages/FUTIL/my_logging.py ,line nÂ°:104
2020-06-27 16:58:29,121 - INFO -  * Running on http://0.0.0.0:50889/ (Press CTRL+C to quit) at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 16:58:29,194 - INFO -  * Restarting with stat at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 16:58:29,455 - INFO - my_logging logger is started. Console : DEBUG. File (/mnt/c/Users/FrÃ©dÃ©ric/Devlopp/t-home/src/pyserve/index.log) : INFO at /home/fred/.local/lib/python3.5/site-packages/FUTIL/my_logging.py ,line nÂ°:104
2020-06-27 16:58:29,901 - WARNING -  * Debugger is active! at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
2020-06-27 16:58:29,902 - INFO -  * Debugger PIN: 267-078-036 at /home/fred/.local/lib/python3.5/site-packages/werkzeug/_internal.py ,line nÂ°:113
